repos:
  - repo: local
    hooks:
      - id: pixi-install
        name: pixi-install
        entry: pixi install
        language: system
        pass_filenames: false

      - id: generate-stubs
        name: regenerate-stubs
        entry: pixi run -e dev generate_stubs
        language: system
        pass_filenames: false

      - id: ruff-format
        name: ruff-format
        entry: pixi run -e dev ruff format
        language: system
        types_or: [python, pyi]
        pass_filenames: true

      - id: check-for-drift
        name: check-for-drift
        entry: git diff --exit-code
        language: system
        pass_filenames: false