site_name: poMTQDTEu8WOPVIyqEDekY # please change accordingly
theme:
  name: material

docs_dir: documentation

markdown_extensions:
  - pymdownx.snippets:
      base_path: ["."]

# nav:
#   - Home: README.md