site_name: q6taaj04do99vgf9cog0gurq6 # please change accordingly
theme:
  name: material

docs_dir: documentation

markdown_extensions:
  - pymdownx.snippets:
      base_path: ["."]

# nav:
#   - Home: README.md